### ISSUE TITLE
Enable support for Amazon Music

### ISSUE THREAD

**Issue by michihupf** [darkdeltagaming/ddgbot-issue-tracker#1]
**Is your feature request related to a problem? Please describe.**
Amazon Music is currently not a supported platform for the music bot.

**Additional context**
Adding support for Amazon Music would benefit some of our server members that use Amazon Music in addition to other, currently supported, music streaming services.

**Comment by michihupf** [comment]
No established discord music bot (like Groovy or Rythm) supports Amazon Music. This would require a lavalink plugin to be written in the first place.

**Comment by oleggtro** [comment]
ja, und Streaming ist nicht erlaubt. Die userbase ist zu klein, also bringt's das nicht
