### ISSUE TITLE
Double Skipping after clearing queue breaks bot

### ISSUE THREAD

**Issue by michihupf** [darkdeltagaming/ddgbot-issue-tracker#3]
**Describe the bug**
When skipping twice in quick succession after clearing the queue and adding new songs breaks the bot for the current session.

**To Reproduce**
1. Clear the queue
2. Add something new to the queue
3. Skip and shortly afterwards skip again
4. Bot will not play anything anymore

**Expected behavior**
Bot plays the desired song.

**Comment by michihupf** [comment]
First idea to fix this would be introducing a skip lock for the entire duration of the skip.

**Comment by michihupf** [comment]
@oleggtro was denkst du wie man das lösen könnte, geht das überhaupt ohne Lock oder muss ich unbedingt ein Lock einführen?

**Comment by oleggtro** [comment]
tbh garnicht. ne skip Action dauert ja nicht so lange. Entweder du lockst die und verbietest so einfach schnelle Skips, oder du baust ne queue für die

**Comment by michihupf** [comment]
Ok dann mach ich ein Lock, das deckt dann auch die Fälle ab wenn zwei Leute gleichzeitig nur einen Track skippen wollen. Danke

**Comment by oleggtro** [comment]
Locken is einfacher, ne Queue schöner.

Du nutzt doch Rust, oder? Dann ist `VecDeque` dein Freund

**Comment by michihupf** [comment]
Warum wäre eine Queue schöner?

**Comment by oleggtro** [comment]
Naja, einfach weil du sonst blocken würdest, und blocken immer nicht soo geil ist.
Nach Möglichkeit designed man Software immer so, dass sie in allen Fällen responsive bleibt (solangs halt vertretbarer Aufwand ist)

**Comment by michihupf** [comment]
Hier sollte alles async laufen, und dieses Problem dadurch eigentlich nicht enstehen oder?

**Comment by oleggtro** [comment]
huh

**Comment by oleggtro** [comment]
check ich nicht
